version: "2"
services:
  nats:
    image: nats:latest
    restart: always
    expose:
      - 4222
      - 6222
    ports:
      - 8222:8222
  monitor:
    build: ./
    image: fourchan-monitor
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /mnt/4cm-db/db:/home/node/app/db
    environment:
      - NATS_URL=nats://nats:4222
      - NODE_ENV=production
      - SQLITE_LOCATION=/home/node/app/db
      - BOARDS=b,pol,biz,adv,trv,news,int
